controller_manager:
  ros__parameters:
    update_rate: 100
    # use_sim_time: true

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
      - acceleration
    state_interfaces:
      - position
      - velocity
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - forearm_joint
      - wrist_carrier_joint
      - wrist_bevel_joint

joint_state_broadcaster:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - forearm_joint
      - wrist_carrier_joint
      - wrist_bevel_joint